apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iris-api-gateway-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: iris
  source:
    repoURL: https://github.com/YOUR_ORG/IRIS
    targetRevision: HEAD
    path: helm/iris-api-gateway
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: iris-prod
  syncPolicy:
    automated: null # Manual sync required for production
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 20
