apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iris-agent-router-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: iris

  source:
    repoURL: https://github.com/teatimetech/iris
    targetRevision: HEAD
    path: helm/iris-agent-router
    helm:
      valueFiles:
        - values-prod.yaml
      parameters:
        - name: image.tag
          value: "latest"

  destination:
    server: https://kubernetes.default.svc
    namespace: iris-prod

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m

  revisionHistoryLimit: 20

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
